name: API-Nota-STG
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy Application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        port: 22
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd nota-staging
          git fetch --all && git checkout staging
          git pull
          cp ~/nota-staging-env/docker-compose-stg.yml .
          cp ~/nota-staging-env/.env .
          docker-compose -f docker-compose-stg.yml run --rm server pip install -r requirements-dev.txt --user --upgrade --no-warn-script-location
          docker-compose -f docker-compose-stg.yml run --rm server python src/manage.py db upgrade
          docker-compose -f docker-compose-stg.yml stop
          docker-compose -f docker-compose-stg.yml up -d server
          git status
