name: API-Nota-STG
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy Application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        port: 22
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd nota-staging
          chmod +x deploy-staging.sh
          ./deploy-staging.sh
